/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ball.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ball.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.beach_ball_red_0_1.geometry} material={materials.material} />
      <mesh geometry={nodes.beach_ball_red_0_2.geometry} material={materials.blue} />
      <mesh geometry={nodes.beach_ball_red_0_3.geometry} material={materials.white} />
      <mesh geometry={nodes.beach_ball_red_0_4.geometry} material={materials.yellow} />
    </group>
  )
}

useGLTF.preload('/ball.glb')
