/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 car_taxi.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car_taxi.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32}>
        <mesh geometry={nodes.Car01_2_DL1002_0.geometry} material={materials.mt_PalleteBR} position={[1.183, -0.742, 0.304]} />
        <mesh geometry={nodes.Car01_2_DL1002_1.geometry} material={materials.mt_Pallete_Yellow} position={[1.183, -0.742, 0.304]} />
        <mesh geometry={nodes.Car01_2_DL1002_2.geometry} material={materials.mt_Pallete_Black} position={[1.183, -0.742, 0.304]} />
        <mesh geometry={nodes.Car01_2_DL1002_3.geometry} material={materials.mt_PalleteBR_Glass} position={[1.183, -0.742, 0.304]} />
      </group>
      <group position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32}>
        <mesh geometry={nodes.Car01_2_DL2002_0.geometry} material={materials.mt_PalleteBR} position={[1.183, 0.186, 0.311]} />
        <mesh geometry={nodes.Car01_2_DL2002_1.geometry} material={materials.mt_Pallete_Yellow} position={[1.183, 0.186, 0.311]} />
        <mesh geometry={nodes.Car01_2_DL2002_2.geometry} material={materials.mt_Pallete_Black} position={[1.183, 0.186, 0.311]} />
        <mesh geometry={nodes.Car01_2_DL2002_3.geometry} material={materials.mt_PalleteBR_Glass} position={[1.183, 0.186, 0.311]} />
      </group>
      <group position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32}>
        <mesh geometry={nodes.Car01_2_DR1002_0.geometry} material={materials.mt_PalleteBR} position={[-1.183, -0.742, 0.304]} />
        <mesh geometry={nodes.Car01_2_DR1002_1.geometry} material={materials.mt_Pallete_Yellow} position={[-1.183, -0.742, 0.304]} />
        <mesh geometry={nodes.Car01_2_DR1002_2.geometry} material={materials.mt_Pallete_Black} position={[-1.183, -0.742, 0.304]} />
        <mesh geometry={nodes.Car01_2_DR1002_3.geometry} material={materials.mt_PalleteBR_Glass} position={[-1.183, -0.742, 0.304]} />
      </group>
      <group position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32}>
        <mesh geometry={nodes.Car01_2_DR2002_0.geometry} material={materials.mt_PalleteBR} position={[-1.183, 0.186, 0.311]} />
        <mesh geometry={nodes.Car01_2_DR2002_1.geometry} material={materials.mt_Pallete_Yellow} position={[-1.183, 0.186, 0.311]} />
        <mesh geometry={nodes.Car01_2_DR2002_2.geometry} material={materials.mt_Pallete_Black} position={[-1.183, 0.186, 0.311]} />
        <mesh geometry={nodes.Car01_2_DR2002_3.geometry} material={materials.mt_PalleteBR_Glass} position={[-1.183, 0.186, 0.311]} />
      </group>
      <group position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32}>
        <mesh geometry={nodes.Car01_2_Taxi_AdT_0.geometry} material={materials.mt_Pallete_Yellow} />
        <mesh geometry={nodes.Car01_2_Taxi_AdT_1.geometry} material={materials.mt_Pallete_Black} />
        <mesh geometry={nodes.Car01_2_Taxi_AdT_2.geometry} material={materials.mt_Pallete_White} />
      </group>
      <mesh geometry={nodes.Car01_2_Taxi_0.geometry} material={materials.mt_PalleteBR} position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32} />
      <mesh geometry={nodes.Car01_2_Taxi_1.geometry} material={materials.mt_Pallete_Yellow} position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32} />
      <mesh geometry={nodes.Car01_2_Taxi_2.geometry} material={materials.mt_PalleteBR_Glass} position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32} />
      <mesh geometry={nodes.Car01_2_Taxi_3.geometry} material={materials.mt_Pallete_Black} position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32} />
      <mesh geometry={nodes.Car01_2_AdF002_0.geometry} material={materials.mt_PalleteBR} position={[-0.001, 0.246, -0.031]} rotation={[-1.576, 0, 0]} scale={0.32} />
      <mesh geometry={nodes.Car01_2_WhBL002_0.geometry} material={materials.mt_PalleteBR} position={[0.322, 0.109, -0.434]} rotation={[-1.576, 0, 0]} scale={0.32} />
      <mesh geometry={nodes.Car01_2_WhBR002_0.geometry} material={materials.mt_PalleteBR} position={[-0.324, 0.109, -0.434]} rotation={[-1.576, 0, 0]} scale={0.32} />
      <mesh geometry={nodes.Car01_2_WhFL002_0.geometry} material={materials.mt_PalleteBR} position={[0.322, 0.113, 0.307]} rotation={[-1.576, 0, 0]} scale={0.32} />
      <mesh geometry={nodes.Car01_2_WhFR002_0.geometry} material={materials.mt_PalleteBR} position={[-0.324, 0.113, 0.307]} rotation={[-1.576, 0, 0]} scale={0.32} />
    </group>
  )
}

useGLTF.preload('/car_taxi.glb')
